### ISSUE TITLE
suggestion: check that "vote label plan name" does not have a 2nd line starting with [x] plan

### ISSUE THREAD

**Issue by mrttao** [Kinematics/NetTally#12]
by default if a post starts with
```
[x] plan something
[x] blahblah
```
then it considers the entire post to be a plan. This is called "vote label plan name" in settings.

This can cause problems when:
a. plans are defined by thread creator (whose votes are excluded by nettally automatically)
b. having a revote (thus the plans are never meant to have any content)
c. when someone edited their post to vote for a plan before it was created

as people who vote for multiple plans are considered the plan creators. like so:
```
[x] plan john
[x] plan alpha
[x] plan horse
```
in this instance, nettally thinks that the poster in question has created plan john
and that plan john is defined as containing plan alpha and plan horse.

I believe this might also cause some sort of recursion issues.
if later someone defines plan horse as voting for plan john.
as I noticed that when this happens some votes end up not being counted at all (probably triggered an anti recursiveness check that omitted their vote to prevent an infinite loop).
the only way to see all votes there is to go to settings and disable "vote label plan name"

My suggestion is to add a verification step.
when nettally determines a post is a "vote label plan name", then it should do one extra verification step of checking to make sure that the 2nd line of the "plan" is not `[x] plan`
if the 2nd line is that, then it is not actually a vote label plan name.

This rule should not break anything even in the case of edge cases
The only edge case I can think of is when someone intentionally starts the 2nd line of their plan with the word plan. like so
```
[x] plan lol
[x] plan with your friends on how to fight the joker
```
This scenario does not break the vote. it will tally correctly.
there would be a spare
```
[x] plan with your friends on how to fight the joker
```
with 1 single vote (the plan creator).
fixable easily by him adding a -

while even if he doesn't fix it it doesn't break anything.
anyone who votes for plan lol and then another plan will be considered as voting for seperate plans as per the same safety check I suggested. thus preventing miscounts where people are counted as having voted for plans they did not vote for.
meaning nothing broke.

**Comment by Kinematics** [comment]
Fixed with the 5.0 release.
