### ISSUE TITLE
Threadmark category support

### ISSUE THREAD

**Issue by Xon** [Kinematics/NetTally#2]
Threadmark groups now have their category outputted in the css, this allows correct detection of if there are a story threadmarks vs other categories instead of blindly picking the first category on the thread.

**Comment by Kinematics** [comment]
I see instances of ThreadmarkCategory_1, ThreadmarkCategory_2, ThreadmarkCategory_4, and ThreadmarkCategory_5.  I assume that ThreadmarkCategory_1 is the primary.

It seems I can use the URL `/threadmarks?category_id=1` to enforce the primary category.  Testing on QQ, including that in the URL doesn't seem to break behavior for systems that don't have the extended threadmarks.  OK, should be workable.

**Comment by Kinematics** [comment]
Fixed in cd508a9749a88159a7d39310e1fae0b58a46bd16

Fix release: 1.9.3
