### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by Angular-Angel** [Kinematics/NetTally#9]
I tried to run the 3.1.3 command line version on Xubuntu, and I got the following error: 

Error:
  An assembly specified in the application dependencies manifest (nettally.deps.json) was not found:
    package: 'CommandLineParser', version: '2.8.0'
    path: 'lib/netstandard2.0/CommandLine.dll'

Checking the directory, there's no lib folder at all, but there's a bin folder, and it has a folder in it labeled 'CommandLineParser'. Is there a mislabelling somewhere, perhaps?

**Comment by Kinematics** [comment]
Well, that's an embarrassing error. I fixed it in the 3.1.4 release. (It's also an easy text editing fix, but might as well get the new version.)

The issue is that it needs to be told to look in the bin folder when searching for dependency libraries.

**Comment by Angular-Angel** [comment]
Did you fix it in the 3.1.4 command line release? Cause I just tried it and got the same error.

Error:
  An assembly specified in the application dependencies manifest (nettally.deps.json) was not found:
    package: 'CommandLineParser', version: '2.8.0'
    path: 'lib/netstandard2.0/CommandLine.dll'
